/*
 * This source file was generated by the Gradle 'init' task
 */
package javatutoral;

import javax.swing.*;

public class App {

    /**
     * Built in class that is required
     */
    public String getGreeting() {
        return "Hello";
    }

    public static void main(String[] args) {

        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new MainFrame();
            }
        });
    }
}
